version: '3.8'

services:

  mysql:
    image: arm64v8/mysql:oracle
    container_name: "mysql"
    platform: linux/arm64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    volumes:
      # путь локальной папки бд
      - ./databases:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1